const types = {
    GET_MANICURE: '@manicure/GET',
    UPDATE_MANICURE: '@manicure/UPDATE',
    ALL_SERVICOS: '@manicure/GET',
    UPDATE_SERVICOS: '@manicure/UPDATE_SERVICOS',
    UPDATE_FORM: '@manicure/UPDATE_FORM',
    UPDATE_AGENDAMENTO: '@manicure/UPDATE_AGENDAMENTO',
    FILTER_AGENDA: '@manicure/FILTER_AGENDA',
    UPDATE_AGENDA: '@manicure/UPDATE_AGENDA',
    UPDATE_COLABORADORES: '@manicure/UPDATE_COLABORADORES',
    SAVE_AGENDAMENTO: '@manicure/SAVE_AGENDAMENTO',
    CLOSE_MODAL_AGENDAMENTO: '@manicure/CLOSE_MODAL_AGENDAMENTO',
    BUSCAR_CLIENTES_REQUEST: '@manicure/BUSCAR_CLIENTES_REQUEST',
    BUSCAR_CLIENTES_SUCCESS: '@manicure/BUSCAR_CLIENTES_SUCCESS',
    BUSCAR_CLIENTES_FAILURE: '@manicure/BUSCAR_CLIENTES_FAILURE',
    LOGIN_SUCCESS: '@manicure/LOGIN_SUCCESS', // Adicione este tipo
};

export default types;